/* ═══════════════════════════════════════════════════════════════════
   NGO OS — Mock Data
   Volunteer profiles, crisis locations, live feed events
   ═══════════════════════════════════════════════════════════════════ */

import type {
  VolunteerProfile,
  CrisisLocation,
  LiveFeedEvent,
  SystemHealth,
} from "./types";

/* ── Volunteer Profiles ─────────────────────────────────────────── */

export const VOLUNTEER_PROFILES: VolunteerProfile[] = [
  {
    id: "vol-001",
    name: "Dr. Ananya Sharma",
    avatar: "🩺",
    skills: ["Medical/Health", "Water/Sanitation"],
    location: "Delhi, India",
    coordinates: [28.6139, 77.209],
    availability: "immediate",
    experience: 12,
    currentLoad: 30,
    organization: "Médecins Sans Frontières",
    phone: "+91-98765-43210",
    email: "ananya.sharma@msf.org",
  },
  {
    id: "vol-002",
    name: "Ibrahim Okonkwo",
    avatar: "🛡️",
    skills: ["Protection", "Shelter", "Logistics"],
    location: "Lagos, Nigeria",
    coordinates: [6.5244, 3.3792],
    availability: "within-24h",
    experience: 8,
    currentLoad: 55,
    organization: "UNHCR",
    phone: "+234-801-234-5678",
    email: "ibrahim.okonkwo@unhcr.org",
  },
  {
    id: "vol-003",
    name: "Maria Gonzalez",
    avatar: "🌊",
    skills: ["Water/Sanitation", "Food Security"],
    location: "Dhaka, Bangladesh",
    coordinates: [23.8103, 90.4125],
    availability: "immediate",
    experience: 6,
    currentLoad: 20,
    organization: "WaterAid",
    phone: "+880-1712-345678",
    email: "maria.gonzalez@wateraid.org",
  },
  {
    id: "vol-004",
    name: "Raj Patel",
    avatar: "🏗️",
    skills: ["Shelter", "Logistics", "Communication"],
    location: "Mumbai, India",
    coordinates: [19.076, 72.8777],
    availability: "within-24h",
    experience: 10,
    currentLoad: 40,
    organization: "Habitat for Humanity",
    phone: "+91-99887-76655",
    email: "raj.patel@habitat.org",
  },
  {
    id: "vol-005",
    name: "Fatima Al-Hassan",
    avatar: "🍞",
    skills: ["Food Security", "Logistics", "Education"],
    location: "Colombo, Sri Lanka",
    coordinates: [6.9271, 79.8612],
    availability: "immediate",
    experience: 5,
    currentLoad: 15,
    organization: "World Food Programme",
    phone: "+94-77-123-4567",
    email: "fatima.alhassan@wfp.org",
  },
  {
    id: "vol-006",
    name: "Dr. Chen Wei",
    avatar: "💊",
    skills: ["Medical/Health"],
    location: "Kathmandu, Nepal",
    coordinates: [27.7172, 85.324],
    availability: "within-48h",
    experience: 15,
    currentLoad: 65,
    organization: "WHO",
    phone: "+977-9841-234567",
    email: "chen.wei@who.int",
  },
  {
    id: "vol-007",
    name: "Amara Diallo",
    avatar: "🔍",
    skills: ["Search & Rescue", "Medical/Health", "Logistics"],
    location: "Nairobi, Kenya",
    coordinates: [-1.2921, 36.8219],
    availability: "immediate",
    experience: 9,
    currentLoad: 25,
    organization: "Red Cross / Red Crescent",
    phone: "+254-722-123456",
    email: "amara.diallo@redcross.org",
  },
  {
    id: "vol-008",
    name: "Priya Nair",
    avatar: "📡",
    skills: ["Communication", "Education", "Protection"],
    location: "Chennai, India",
    coordinates: [13.0827, 80.2707],
    availability: "within-24h",
    experience: 4,
    currentLoad: 10,
    organization: "UNICEF",
    phone: "+91-98765-11223",
    email: "priya.nair@unicef.org",
  },
  {
    id: "vol-009",
    name: "Omar Yusuf",
    avatar: "🚛",
    skills: ["Logistics", "Food Security", "Shelter"],
    location: "Karachi, Pakistan",
    coordinates: [24.8607, 67.0011],
    availability: "immediate",
    experience: 7,
    currentLoad: 45,
    organization: "CARE International",
    phone: "+92-300-1234567",
    email: "omar.yusuf@care.org",
  },
  {
    id: "vol-010",
    name: "Sarah Mitchell",
    avatar: "🏥",
    skills: ["Medical/Health", "Water/Sanitation", "Education"],
    location: "Yangon, Myanmar",
    coordinates: [16.8661, 96.1951],
    availability: "standby",
    experience: 11,
    currentLoad: 70,
    organization: "Doctors Without Borders",
    phone: "+95-9-123-456789",
    email: "sarah.mitchell@dwb.org",
  },
  {
    id: "vol-011",
    name: "Kwame Asante",
    avatar: "⛺",
    skills: ["Shelter", "Protection", "Search & Rescue"],
    location: "Accra, Ghana",
    coordinates: [5.6037, -0.187],
    availability: "within-24h",
    experience: 6,
    currentLoad: 35,
    organization: "Oxfam",
    phone: "+233-20-123-4567",
    email: "kwame.asante@oxfam.org",
  },
  {
    id: "vol-012",
    name: "Lakshmi Devi",
    avatar: "💧",
    skills: ["Water/Sanitation", "General"],
    location: "Patna, India",
    coordinates: [25.6093, 85.1376],
    availability: "immediate",
    experience: 3,
    currentLoad: 5,
    organization: "Action Against Hunger",
    phone: "+91-94311-22334",
    email: "lakshmi.devi@actionagainsthunger.org",
  },
];

/* ── Crisis Locations (for map) ─────────────────────────────────── */

export const CRISIS_LOCATIONS: CrisisLocation[] = [
  {
    id: "crisis-001",
    name: "Sector 7 Flood Zone",
    coordinates: [25.6, 85.1],
    urgency: "critical",
    category: "Water/Sanitation",
    population: 1200,
    description: "Severe flooding has contaminated primary water supply. 1,200 people without clean water.",
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    status: "active",
  },
  {
    id: "crisis-002",
    name: "Dhaka Medical Emergency",
    coordinates: [23.81, 90.41],
    urgency: "critical",
    category: "Medical/Health",
    population: 3500,
    description: "Hospital overwhelmed. Critical shortage of medical supplies and personnel.",
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    status: "active",
  },
  {
    id: "crisis-003",
    name: "Chennai Shelter Crisis",
    coordinates: [13.08, 80.27],
    urgency: "high",
    category: "Shelter",
    population: 800,
    description: "Cyclone damage. 800 families need emergency shelter and supplies.",
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    status: "active",
  },
  {
    id: "crisis-004",
    name: "Nepal Food Distribution",
    coordinates: [27.72, 85.32],
    urgency: "high",
    category: "Food Security",
    population: 2000,
    description: "Remote villages cut off from supply routes. Food stocks critically low.",
    timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    status: "in-progress",
  },
  {
    id: "crisis-005",
    name: "Colombo Communication Down",
    coordinates: [6.93, 79.86],
    urgency: "medium",
    category: "Communication",
    population: 500,
    description: "Network infrastructure damaged. Field teams unable to coordinate.",
    timestamp: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    status: "in-progress",
  },
  {
    id: "crisis-006",
    name: "Mumbai Logistics Bottleneck",
    coordinates: [19.08, 72.88],
    urgency: "medium",
    category: "Logistics",
    population: 1500,
    description: "Supply convoy delayed. Road blockage preventing aid delivery.",
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    status: "active",
  },
  {
    id: "crisis-007",
    name: "Karachi Protection Concern",
    coordinates: [24.86, 67.0],
    urgency: "high",
    category: "Protection",
    population: 350,
    description: "Vulnerable populations at risk. Need immediate protection measures.",
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    status: "active",
  },
];

/* ── Live Feed Events ───────────────────────────────────────────── */

export const LIVE_FEED_EVENTS: LiveFeedEvent[] = [
  {
    id: "feed-001",
    type: "crisis",
    message: "New flood report: Sector 7, Bihar — 1,200 affected. Water contamination confirmed.",
    timestamp: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    urgency: "critical",
    location: "Bihar, India",
  },
  {
    id: "feed-002",
    type: "volunteer",
    message: "Dr. Ananya Sharma deployed to Dhaka Medical Emergency. ETA: 4 hours.",
    timestamp: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    urgency: "high",
    location: "Dhaka, Bangladesh",
  },
  {
    id: "feed-003",
    type: "update",
    message: "Nepal food convoy cleared road blockage. Delivery to 3 villages resuming.",
    timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    urgency: "medium",
    location: "Kathmandu, Nepal",
  },
  {
    id: "feed-004",
    type: "alert",
    message: "Cyclone warning upgraded: Chennai region may face Category 3 storm in 48h.",
    timestamp: new Date(Date.now() - 22 * 60 * 1000).toISOString(),
    urgency: "critical",
    location: "Chennai, India",
  },
  {
    id: "feed-005",
    type: "resolution",
    message: "Colombo communication hub restored. Field coordination back online.",
    timestamp: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    urgency: "low",
    location: "Colombo, Sri Lanka",
  },
  {
    id: "feed-006",
    type: "crisis",
    message: "New report: Karachi displacement camp overcrowded. Protection risks escalating.",
    timestamp: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    urgency: "high",
    location: "Karachi, Pakistan",
  },
  {
    id: "feed-007",
    type: "volunteer",
    message: "WaterAid team mobilized for Bihar. 5,000 purification tablets dispatched.",
    timestamp: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
    urgency: "high",
    location: "Bihar, India",
  },
  {
    id: "feed-008",
    type: "update",
    message: "Mumbai logistics reroute successful. Alternate supply path identified via NH48.",
    timestamp: new Date(Date.now() - 70 * 60 * 1000).toISOString(),
    urgency: "medium",
    location: "Mumbai, India",
  },
];

/* ── System Health Baseline ─────────────────────────────────────── */

export const SYSTEM_HEALTH: SystemHealth = {
  aiEngine: { status: "online", latency: 120 },
  dataIngestion: { status: "online", throughput: 94 },
  matchingEngine: { status: "online", accuracy: 97 },
  communications: { status: "online", uptime: 99.7 },
};
