/* ═══════════════════════════════════════════════════════════════════
   NGO OS — Mock Data
   Volunteer profiles, crisis locations, live feed events
   ═══════════════════════════════════════════════════════════════════ */

import type {
  VolunteerProfile,
  CrisisLocation,
  LiveFeedEvent,
  SystemHealth,
} from "./types";

/* ── Volunteer Profiles ─────────────────────────────────────────── */

export const VOLUNTEER_PROFILES: VolunteerProfile[] = [
  {
    id: "vol-001",
    name: "Dr. Ananya Sharma",
    avatar: "🩺",
    skills: ["Medical/Health", "Water/Sanitation"],
    location: "Delhi, India",
    coordinates: [28.6139, 77.209],
    availability: "immediate",
    experience: 12,
    currentLoad: 30,
    organization: "Médecins Sans Frontières",
    phone: "+91-98765-43210",
    email: "ananya.sharma@msf.org",
  },
  {
    id: "vol-002",
    name: "Ibrahim Okonkwo",
    avatar: "🛡️",
    skills: ["Protection", "Shelter", "Logistics"],
    location: "Lagos, Nigeria",
    coordinates: [6.5244, 3.3792],
    availability: "within-24h",
    experience: 8,
    currentLoad: 55,
    organization: "UNHCR",
    phone: "+234-801-234-5678",
    email: "ibrahim.okonkwo@unhcr.org",
  },
  {
    id: "vol-003",
    name: "Maria Gonzalez",
    avatar: "🌊",
    skills: ["Water/Sanitation", "Food Security"],
    location: "Dhaka, Bangladesh",
    coordinates: [23.8103, 90.4125],
    availability: "immediate",
    experience: 6,
    currentLoad: 20,
    organization: "WaterAid",
    phone: "+880-1712-345678",
    email: "maria.gonzalez@wateraid.org",
  },
  {
    id: "vol-004",
    name: "Raj Patel",
    avatar: "🏗️",
    skills: ["Shelter", "Logistics", "Communication"],
    location: "Mumbai, India",
    coordinates: [19.076, 72.8777],
    availability: "within-24h",
    experience: 10,
    currentLoad: 40,
    organization: "Habitat for Humanity",
    phone: "+91-99887-76655",
    email: "raj.patel@habitat.org",
  },
  {
    id: "vol-005",
    name: "Fatima Al-Hassan",
    avatar: "🍞",
    skills: ["Food Security", "Logistics", "Education"],
    location: "Colombo, Sri Lanka",
    coordinates: [6.9271, 79.8612],
    availability: "immediate",
    experience: 5,
    currentLoad: 15,
    organization: "World Food Programme",
    phone: "+94-77-123-4567",
    email: "fatima.alhassan@wfp.org",
  },
  {
    id: "vol-006",
    name: "Dr. Chen Wei",
    avatar: "💊",
    skills: ["Medical/Health"],
    location: "Kathmandu, Nepal",
    coordinates: [27.7172, 85.324],
    availability: "within-48h",
    experience: 15,
    currentLoad: 65,
    organization: "WHO",
    phone: "+977-9841-234567",
    email: "chen.wei@who.int",
  },
  {
    id: "vol-007",
    name: "Amara Diallo",
    avatar: "🔍",
    skills: ["Search & Rescue", "Medical/Health", "Logistics"],
    location: "Nairobi, Kenya",
    coordinates: [-1.2921, 36.8219],
    availability: "immediate",
    experience: 9,
    currentLoad: 25,
    organization: "Red Cross / Red Crescent",
    phone: "+254-722-123456",
    email: "amara.diallo@redcross.org",
  },
  {
    id: "vol-008",
    name: "Priya Nair",
    avatar: "📡",
    skills: ["Communication", "Education", "Protection"],
    location: "Chennai, India",
    coordinates: [13.0827, 80.2707],
    availability: "within-24h",
    experience: 4,
    currentLoad: 10,
    organization: "UNICEF",
    phone: "+91-98765-11223",
    email: "priya.nair@unicef.org",
  },
  {
    id: "vol-009",
    name: "Omar Yusuf",
    avatar: "🚛",
    skills: ["Logistics", "Food Security", "Shelter"],
    location: "Karachi, Pakistan",
    coordinates: [24.8607, 67.0011],
    availability: "immediate",
    experience: 7,
    currentLoad: 45,
    organization: "CARE International",
    phone: "+92-300-1234567",
    email: "omar.yusuf@care.org",
  },
  {
    id: "vol-010",
    name: "Sarah Mitchell",
    avatar: "🏥",
    skills: ["Medical/Health", "Water/Sanitation", "Education"],
    location: "Yangon, Myanmar",
    coordinates: [16.8661, 96.1951],
    availability: "standby",
    experience: 11,
    currentLoad: 70,
    organization: "Doctors Without Borders",
    phone: "+95-9-123-456789",
    email: "sarah.mitchell@dwb.org",
  },
  {
    id: "vol-011",
    name: "Kwame Asante",
    avatar: "⛺",
    skills: ["Shelter", "Protection", "Search & Rescue"],
    location: "Accra, Ghana",
    coordinates: [5.6037, -0.187],
    availability: "within-24h",
    experience: 6,
    currentLoad: 35,
    organization: "Oxfam",
    phone: "+233-20-123-4567",
    email: "kwame.asante@oxfam.org",
  },
  {
    id: "vol-012",
    name: "Lakshmi Devi",
    avatar: "💧",
    skills: ["Water/Sanitation", "General"],
    location: "Patna, India",
    coordinates: [25.6093, 85.1376],
    availability: "immediate",
    experience: 3,
    currentLoad: 5,
    organization: "Action Against Hunger",
    phone: "+91-94311-22334",
    email: "lakshmi.devi@actionagainsthunger.org",
  },
];

/* ── Crisis Locations (for map) ─────────────────────────────────── */

export const CRISIS_LOCATIONS: CrisisLocation[] = [
  {
    id: "crisis-001",
    name: "Nadia Flood Zone",
    coordinates: [23.47, 88.55],
    urgency: "critical",
    category: "Flood Relief",
    population: 1200,
    description: "Severe flooding has submerged primary villages. 1,200 people need immediate evacuation.",
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    status: "active",
  },
  {
    id: "crisis-002",
    name: "Murshidabad Medical Emergency",
    coordinates: [24.18, 88.28],
    urgency: "critical",
    category: "Medical Team",
    population: 3500,
    description: "Local clinics overwhelmed due to waterborne disease outbreak. Critical shortage of medical personnel.",
    timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    status: "active",
  },
  {
    id: "crisis-003",
    name: "Kendrapara Relief Center",
    coordinates: [20.50, 86.42],
    urgency: "high",
    category: "Ration Distribution",
    population: 800,
    description: "Cyclone damage disrupted supply chains. 800 families need emergency ration supplies.",
    timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    status: "active",
  },
  {
    id: "crisis-004",
    name: "Patna Anganwadi Support",
    coordinates: [25.59, 85.13],
    urgency: "high",
    category: "Anganwadi Support",
    population: 2000,
    description: "Children in local Anganwadi centers lacking basic nutritional supplies.",
    timestamp: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    status: "in-progress",
  },
  {
    id: "crisis-005",
    name: "Puri Coastal Alert",
    coordinates: [19.81, 85.83],
    urgency: "medium",
    category: "Protection",
    population: 500,
    description: "Coastal villages at risk of high tide surges. Evacuation routes being prepared.",
    timestamp: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    status: "in-progress",
  },
  {
    id: "crisis-006",
    name: "Kolkata Logistics Bottleneck",
    coordinates: [22.57, 88.36],
    urgency: "medium",
    category: "Logistics",
    population: 1500,
    description: "Supply convoy delayed due to waterlogged roads in the metropolis.",
    timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    status: "active",
  },
  {
    id: "crisis-007",
    name: "Malda Shelter Crisis",
    coordinates: [25.00, 88.14],
    urgency: "high",
    category: "Shelter",
    population: 350,
    description: "Displaced families need immediate shelter support.",
    timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    status: "active",
  },
];

/* ── Live Feed Events ───────────────────────────────────────────── */

export const LIVE_FEED_EVENTS: LiveFeedEvent[] = [
  {
    id: "feed-001",
    type: "crisis",
    message: "New flood report: Nadia, West Bengal — 1,200 affected. Urgent evacuation required.",
    timestamp: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    urgency: "critical",
    location: "Nadia, West Bengal",
  },
  {
    id: "feed-002",
    type: "volunteer",
    message: "Dr. Anjali Desai deployed to Murshidabad Medical Emergency. ETA: 4 hours.",
    timestamp: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    urgency: "high",
    location: "Murshidabad, West Bengal",
  },
  {
    id: "feed-003",
    type: "update",
    message: "Kendrapara ration convoy cleared road blockage. Delivery resuming.",
    timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    urgency: "medium",
    location: "Kendrapara, Odisha",
  },
  {
    id: "feed-004",
    type: "alert",
    message: "Nutrition supplies critically low in Patna Anganwadi centers.",
    timestamp: new Date(Date.now() - 22 * 60 * 1000).toISOString(),
    urgency: "high",
    location: "Patna, Bihar",
  },
  {
    id: "feed-005",
    type: "resolution",
    message: "Kolkata logistics route restored. Supply trucks moving.",
    timestamp: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    urgency: "low",
    location: "Kolkata, West Bengal",
  },
  {
    id: "feed-006",
    type: "crisis",
    message: "New report: Malda displaced camp overcrowded. Need more shelter kits.",
    timestamp: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    urgency: "high",
    location: "Malda, West Bengal",
  },
  {
    id: "feed-007",
    type: "volunteer",
    message: "Hope Foundation team mobilized for Nadia. 5 boats dispatched.",
    timestamp: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
    urgency: "high",
    location: "Nadia, West Bengal",
  },
  {
    id: "feed-008",
    type: "update",
    message: "Puri coastal warning downgraded. High tide subsided.",
    timestamp: new Date(Date.now() - 70 * 60 * 1000).toISOString(),
    urgency: "medium",
    location: "Puri, Odisha",
  },
];

/* ── System Health Baseline ─────────────────────────────────────── */

export const SYSTEM_HEALTH: SystemHealth = {
  aiEngine: { status: "online", latency: 120 },
  dataIngestion: { status: "online", throughput: 94 },
  matchingEngine: { status: "online", accuracy: 97 },
  communications: { status: "online", uptime: 99.7 },
};
